service: githubaction-lambda-test

provider:
  name: aws
  runtime: nodejs14.x
  stage: main
  region: us-east-1

functions:
  hello:
    handler: handler.generateRandomNumber
    events: 
    - http: ANY {proxy+}
    - http: ANY /
    