service: githubaction-lambda-test

provider:
  name: aws
  runtime: nodejs14.x
  stage: main
  region: us-east-1
  timeout: 30 # seconds
  memorySize: 128 # mb

functions:
  BJIT:
    handler: handler.generateRandomNumber
    - http: ANY {proxy+}
    - http: ANY /
