name: Deploy Lambda #Name of action
# Triggers the workflow on push request for the main branch
on:
  push:
    branches:
      - main
# A workflows run in made up of one or more jobs that can run sequestially or parallel 
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # The type of runner that job will run on
    strategy:
      matrix:
        node-version: [14.x]
    # Stepls represent a sequence of tasks that will be executed as a part of the job 
    steps:

    - uses: actions/checkout@v2  # Telling the gitactions workflows to download the content of repo within current workspace
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@v1
      with:
        args: deploy
      env:
        
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}